steps:
  - name: node
    entrypoint: yarn
    args: ['install', '--frozen-lockfile']
  - name: node
    entrypoint: yarn
    args: ['build']
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./build", "gs://developer.kazaplan.com"]